<?php

namespace DI\correct;
require_once "IPowerSupply.php";

class WaterPowerSupplier implements IPowerSupply
{
    function ConsumeEnergy()
    {
        echo "here take my energy for whatever you need... generated by my water turbines!\r\n";
    }
}