<?php

namespace DI\correct;

require_once "IPowerSupply.php";

class WindPowerSupplier implements IPowerSupply
{
    function ConsumeEnergy()
    {
        echo "here take my energy for whatever you need... generated by my wind turbines!\r\n";
    }
}